launch:
  ros__parameters:
    joy: true   # ジョイスティック機能を有効にするか（true = 有効）

# ジョイスティックドライバの設定
joy_node:
  ros__parameters:
    device: /dev/input/js0     # 使用するジョイスティックデバイスのパス
    deadzone: 0.3              # デッドゾーン設定（0.0〜1.0）
    autorepeat_rate: 20.0      # 自動リピート間隔 [Hz]

# ジョイスティック操作でTwistメッセージを生成
teleop_twist_joy_node:
  ros__parameters:
    axis_linear:               # 前後方向のスティック軸
      x: 1
    scale_linear:              # 通常モードの直進スピード倍率
      x: 0.2
    scale_linear_turbo:        # ターボモード時のスピード倍率
      x: 1.2
    axis_angular:              # 回転方向（ヨー）のスティック軸
      yaw: 3
    scale_angular:             # 回転スピード倍率
      yaw: 1.0
    enable_button: 4           # 操作有効化トグルのボタン番号
    enable_turbo_button: 5     # ターボモード有効化のボタン番号

# ros2_control_nodeに渡すパラメータ
/**:
  ros__parameters:
    update_rate: 100                 # ノードの更新周期 [Hz]
    left_wheel_names: ["left_wheel_joint"]   # 左車輪ジョイント名（URDFに一致）
    right_wheel_names: ["right_wheel_joint"] # 右車輪ジョイント名（URDFに一致）
    wheel_separation: 0.4615            # 左右ホイール間の距離 [m]
    wheel_radius: 0.145                 # ホイール半径 [m]
    use_stamped_vel: false             # geometry_msgs/TwistStamped を使うか
    base_frame_id: base_link           # ベースフレームの名前
    odom_frame_id: odom                # オドメトリフレームの名前
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
