launch: # 起動パラメータ
  ros__parameters:
    joy: true   # ジョイスティックの使用を有効にする
    livox: true  # Livox LiDARの使用を有効にする
    urg: true   # URG LiDARの使用を有効にする
    rviz: true  # RVizの使用を有効にする

icart_mini_driver_node:
    ros__parameters:
            odom_frame_id: 'odom'   # odomフレームのID
            base_frame_id: 'base_footprint'  # ベースフレームのID
            Hz: 40  # ノードの更新頻度（Hz単位）
            left_wheel_joint: 'left_wheel_joint'    # 左ホイールのジョイント名
            right_wheel_joint: 'right_wheel_joint'   # 右ホイールのジョイント名
            liner_vel_lim: 1.5  # 並進速度の制限（m/s）
            liner_accel_lim: 1.5    # 並進加速度の制限（m/s^2）
            angular_vel_lim: 3.14   # 角速度の制限（rad/s）
            angular_accel_lim: 3.14 # 角加速度の制限（rad/s^2）
            calculate_odom_from_ypspur: true    # YPSPURからのオドメトリ計算を有効にする
            publish_odom_tf: true  # オドメトリのTFをパブリッシュするかどうか

joy_node:
    ros__parameters:
        device: /dev/input/js0  # ジョイスティックデバイスのパス
        deadzone: 0.3  # デッドゾーンの設定（0.0から1.0）
        autorepeat_rate: 20.0  # 自動リピートレート（Hz単位）

teleop_twist_joy_node:
    ros__parameters:
        axis_linear:    # 進方向のジョイスティック軸の設定
            x: 1
        scale_linear:   # 並進速度のスケール（通常モード）
            x: 0.6
        scale_linear_turbo: # 並進速度のスケール（ターボモード）
            x: 1.2
        axis_angular:   # 角速度（yaw軸）に対応するジョイスティックの軸番号
            yaw: 3
        scale_angular:  # 角速度のスケール
            yaw: 1.0
        enable_button: 4    # ジョイスティック操作を有効にするボタン番号
        enable_turbo_button: 5  # ターボモードを有効にするボタン番号

livox_lidar_publisher:
  ros__parameters:
    xfer_format: 0              # 0: PointCloud2形式で出力（Rviz2対応）、1: Livox独自形式（カスタムMsg）
    multi_topic: 0              # 0: 全てのLiDARが同じトピックを使用、1: LiDARごとに個別のトピックを使用
    data_src: 0                 # 0: LiDARからの生データ、他は無効（未使用）
    publish_freq: 10.0          # データの発行頻度（Hz）。例: 5.0, 10.0, 20.0など
    output_data_type: 0         # 出力先タイプ（通常は0でROSに出力）
    frame_id: "livox_frame"     # 出力データに使用するTFのフレームID
    lvx_file_path: "/home/livox/livox_test.lvx"  # 録画ファイルのパス（使用しない場合は空でも可）
    # user_config_path: "/your/path/to/MID360_config.json"  # LiDARのネットワークやIP設定などの詳細構成（launchで有効化済み）
    cmdline_input_bd_code: "livox0000000001"     # LiDARデバイスのIDを手動で指定（必要に応じて）

urg_node:
  ros__parameters:
    serial_port: '/dev/sensors/hokuyo'  # シリアルポートの指定
    serial_baud: 115200 # ボーレートの指定
    frame_id : 'laser'  # 出力データのフレームID
    calibrate_time : false  # 時間のキャリブレーションを行うかどうか
    synchronize_time : false    # 時間の同期を行うかどうか
    publish_intensity : false   # 強度データをパブリッシュするかどうか
    publish_multiecho : false   # マルチエコーをパブリッシュするかどうか
    error_limit : 4 # エラーの制限値
    error_reset_period : 5.0    # エラーリセットの周期
    diagnostics_tolerance : 0.05    # 診断の許容値
    diagnostics_window_time : 5.0   # 診断のウィンドウ時間
    time_offset : 0.0   # 時間オフセット
    angle_min : -1.57   # 最小角度
    angle_max : 1.57    # 最大角度
    skip : 0    # スキップするデータ数
    cluster : 1   # クラスタリングの設定

ekf_filter_node:
  ros__parameters:
    frequency: 40.0 # フィルタの更新頻度（Hz）
    sensor_timeout: 0.5 # センサーのタイムアウト時間（秒）
    two_d_mode: true    # 2Dモードを有効にするかどうか
    transform_time_offset: 0.0  # 変換の時間オフセット
    transform_timeout: 0.0  # 変換のタイムアウト時間
    map_frame: map             # 地図フレームのID
    odom_frame: odom           # オドメトリフレームのID
    base_link_frame: base_link  # ベースリンクフレームのID
    world_frame: odom           # ワールドフレームのID
    publish_tf: true           # TFをパブリッシュするかどうか
    imu0_remove_gravitational_acceleration: true # IMUの重力加速度を除去するかどうか
    odom0: /odom         # オドメトリのトピック名
    odom0_config:   [false, false, false,
                    false, false, false,
                    true , true , false,
                    false , false , true,
                    false, false, false]
    imu0: /livox/imu    # IMUのトピック名
    imu0_config:    [false, false, false,
                    false, false, true,
                    false, false, false,
                    true , true , true,
                    false, false, true]
                    # [x, y, z,
                    # roll, pitch, yaw,
                    # x_vel, y_vel, z_vel,
                    # roll_vel, pitch_vel, yaw_vel,
                    # x_accel, y_accel, z_accel]
